DROP TABLE IF EXISTS Version CASCADE;
DROP TABLE IF EXISTS TrainingLog CASCADE;
DROP TABLE IF EXISTS Rotation CASCADE;
DROP TABLE IF EXISTS Exercise CASCADE;
DROP TABLE IF EXISTS Client CASCADE;
DROP TABLE IF EXISTS BodyWeight CASCADE;
DROP TABLE IF EXISTS ExerciseType CASCADE;
DROP TABLE IF EXISTS ExerciseFocus CASCADE;

CREATE TABLE IF NOT EXISTS Version (
    num INT NOT NULL
);

CREATE TABLE Client (
	id SERIAL PRIMARY KEY,
	firstName TEXT NOT NULL,
	lastName TEXT NOT NULL,
	email TEXT NOT NULL
);

CREATE TABLE ExerciseType (
	Id SERIAL PRIMARY KEY,
	T TEXT NOT NULL,
	Description TEXT NOT NULL
);

CREATE TABLE ExerciseFocus (
	Id SERIAL PRIMARY KEY,
	Focus TEXT NOT NULL
);

CREATE TABLE Exercise (
	Id SERIAL PRIMARY KEY,
	Name TEXT NOT NULL,
	TypeID INT NOT NULL,
	FocusID INT,
    FOREIGN KEY (typeID) REFERENCES ExerciseType(id),
    FOREIGN KEY (focusID) REFERENCES ExerciseFocus(id)
);

CREATE TABLE Rotation (
	Id SERIAL PRIMARY KEY,
	UserID INTEGER NOT NULL,
	StartDate DATE NOT NULL,
	EndDate DATE NOT NULL,
	FOREIGN KEY (userID) REFERENCES Client(id)
);

CREATE TABLE BodyWeight (
    Id SERIAL PRIMARY KEY,
	UserID INTEGER NOT NULL,
	Weight FLOAT NOT NULL,
    Date DATE NOT NULL,
	FOREIGN KEY (userID) REFERENCES Client(id)
);

CREATE TABLE TrainingLog (
    Id SERIAL PRIMARY KEY,
	UserID INTEGER NOT NULL,
	ExerciseID INTEGER NOT NULL,
	DatePerformed DATE NOT NULL DEFAULT CURRENT_DATE,
	Weight FLOAT NOT NULL,
	Sets SMALLINT NOT NULL,
	Reps SMALLINT NOT NULL,
	Intensity FLOAT,
	FOREIGN KEY (userID) REFERENCES Client(ID),
	FOREIGN KEY (exerciseID) REFERENCES Exercise(ID)
);
