DROP TABLE IF EXISTS Version CASCADE;
DROP TABLE IF EXISTS TrainingLog CASCADE;
DROP TABLE IF EXISTS Rotations CASCADE;
DROP TABLE IF EXISTS Maxes CASCADE;
DROP TABLE IF EXISTS Exercises CASCADE;
DROP TABLE IF EXISTS Clients CASCADE;
DROP TABLE IF EXISTS BodyWeight CASCADE;
DROP TABLE IF EXISTS ExerciseTypes CASCADE;
DROP TABLE IF EXISTS ExerciseFocus CASCADE;

CREATE TABLE IF NOT EXISTS Version (
    num INT NOT NULL
);

CREATE TABLE Clients (
	id SERIAL PRIMARY KEY,
	firstName TEXT NOT NULL,
	lastName TEXT NOT NULL,
	email TEXT NOT NULL
);

CREATE TABLE ExerciseTypes (
	id SERIAL PRIMARY KEY,
	_type TEXT NOT NULL,
	description TEXT NOT NULL
);

CREATE TABLE ExerciseFocus (
	id SERIAL PRIMARY KEY,
	focus TEXT NOT NULL
);

CREATE TABLE Exercises (
	id SERIAL PRIMARY KEY,
	name TEXT NOT NULL,
	typeID INT NOT NULL,
	focusID INT,
    FOREIGN KEY (typeID) REFERENCES ExerciseTypes(id),
    FOREIGN KEY (focusID) REFERENCES ExerciseFocus(id)
);

CREATE TABLE Rotations (
	id SERIAL PRIMARY KEY,
	userID INTEGER NOT NULL,
	startDate DATE NOT NULL,
	endDate DATE NOT NULL,
	FOREIGN KEY (userID) REFERENCES Clients(id)
);

CREATE TABLE BodyWeight (
	userID INTEGER NOT NULL,
	weight FLOAT NOT NULL,
	FOREIGN KEY (userID) REFERENCES Clients(id)
);

CREATE TABLE TrainingLog (
	userID INTEGER NOT NULL,
	exerciseID INTEGER NOT NULL,
	datePermormed DATE NOT NULL DEFAULT CURRENT_DATE,
	weight FLOAT NOT NULL,
	sets SMALLINT NOT NULL,
	reps SMALLINT NOT NULL,
	intensity FLOAT,
	FOREIGN KEY (userID) REFERENCES Clients(ID),
	FOREIGN KEY (exerciseID) REFERENCES Exercises(ID)
);
